### PR TITLE
Test against canonical data

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by Cadair** [comment]
The issue here seems to be we aren't converting from a buffer to a numpy array correctly for the GZIP case. I think this looks like  the right bit of the cfitsio code that we need to replicate:

https://github.com/astropy/astropy/blob/a8cb1668d4835562b89c0d0b3448ac72ca44db63/cextern/cfitsio/lib/imcompress.c#L6345-L6388

**Comment by Cadair** [comment]
@astrofrog I am giving up here for the day, but given the GZIP byte length disparity do you have any ideas how I can finish the test? Should I just not bother?

**Comment by Cadair** [comment]
I don't know why pytest-openfiles hates this. The file should be closed as the context manager has exited. I have asked on chat, and I will take another look later, for now I think we can merge as is.

**Review by astrofrog — APPROVED** [review]
I wonder if the open file detection happens before the fixture resumes execution and exits the context manager? Either way I think this is fine to merge for now so feel free to merge.

**Comment by Cadair** [comment]
I experimented with that by putting in prints and breakpoints. The context manager definitely exits. I am going to try disabling memmap and see if that fixes it.

**Pull request merged**
